[params]
disable=0
sample_rate=20
output_dir=C:\Users\g04590\Documents\PiBoSo\GP Bikes\LOGGER
flush_each_event=0

auto_convert=1
converter_python=py
converter_script=C:\Users\g04590\projects\GPBikesPluginLogger\mxbrec_gpb_to_piboso_csv_lap_scaled_v2.py

; optional debug breadcrumbs
debug_log=0